export default 
{
    Auth: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJBSjVBVGlObUlWRDRsSURWZVdMc0JpR1Z4VnFqSGtnR2ZyYmtOdnlZUlhjIn0.eyJleHAiOjE2NjY2MzE4ODMsImlhdCI6MTY2NjYxNzQ4MywianRpIjoiMDU2MDI5MTAtOWVhNy00NTBhLTliODgtNDJlMjY5MmZmYTZjIiwiaXNzIjoiaHR0cHM6Ly90ZXN0LWFwaS5icmFtZS1nYW1pZmljYXRpb24uY29tL2tleWNsb2FrL2F1dGgvcmVhbG1zL2JyYW1lIiwiYXVkIjoiYmUtc2VydmljZSIsInN1YiI6ImQwZGY5NjZlLWZmOTAtNGJmZi04ZDkzLWJmYjA4YzI4ZGU5NCIsInR5cCI6IkJlYXJlciIsImF6cCI6ImZlLWNsaWVudCIsInNlc3Npb25fc3RhdGUiOiJhMDk2MzMwNi1kYThmLTRjODMtOTdjNy1mYTEwY2MxNzc2NWUiLCJhY3IiOiIxIiwiYWxsb3dlZC1vcmlnaW5zIjpbImh0dHBzOi8vdGVzdC1hcHAuYnJhbWUtZ2FtaWZpY2F0aW9uLmNvbSIsInRlc3QtYXBwLmJyYW1lLWdhbWlmaWNhdGlvbi5jb20iXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkVESVRPUiIsIlZJRVdFUiIsIlVTRVJfQURNSU4iXX0sInJlc291cmNlX2FjY2VzcyI6eyJiZS1zZXJ2aWNlIjp7InJvbGVzIjpbIkVESVRPUiIsIlZJRVdFUiIsIlVTRVJfQURNSU4iXX19LCJzY29wZSI6ImVtYWlsIHByb2ZpbGUiLCJlbWFpbF92ZXJpZmllZCI6ZmFsc2UsInJvbGUiOlsiRURJVE9SIiwiVklFV0VSIiwiVVNFUl9BRE1JTiJdLCJjb21wYW55X2lkIjoiMzNiZTIyZTMtYTc2Yi0xMWViLThlNTEtNzVhMDFiYTlmMmNjIiwibmFtZSI6Ik1pb2RyYWcgVG9kb3JvdmljIiwicHJlZmVycmVkX3VzZXJuYW1lIjoibG90dXNAYnJhbWUuY2giLCJnaXZlbl9uYW1lIjoiTWlvZHJhZyIsImZhbWlseV9uYW1lIjoiVG9kb3JvdmljIiwiZW1haWwiOiJsb3R1c0BicmFtZS5jaCJ9.ecfM69MpD9-p33ahtPCQp-1td2mnhBPw_v8U5SF8Z-S3dpaFIcEa5lLGG11xFqFXwripPmsAptGXiLjBgo0kKOc14pZnSzOqoQJvUSqY_Tks8_jsCndGXSjyKl2OyeTM-gZ9FfM41G08IsLddLMtWtiMwdkL3n7Ndv3z5H6Uzy06pENPHcMa2xqnYGsC5xgk-Bwecdrbp4fOT3dZEYzC01Z7m2NmPSLOEacKQ7XuhjO-oPgxZ0ckfPTIeqwpX4xATtARKWNrJ-CQN9NQ27c6ZUhtsHt28mcmY4hh-X_VeRF4bINtXJVdoF3thiq8dvwcZSh2FK1s2MZEb-OOm-c63g',
    CompanyId: '33be22e3-a76b-11eb-8e51-75a01ba9f2cc',
    PostPrizeEndpoint: 'https://test-serverless-api.brame-gamification.com/prize-management/prizes',
    DeletePrizeEndpoint: 'https://test-serverless-api.brame-gamification.com/prize-management/prizes/delete/',
    PostPoolEndpoint: "https://test-serverless-api.brame-gamification.com/prize-management/pools/",
    DeletePoolEndpoint: "https://test-serverless-api.brame-gamification.com/prize-management/pools/delete",
    GetCampaignEndpoint: "https://test-api.brame-gamification.com/campaign/search",
    DeleteCampaignEndpoint: "https://test-api.brame-gamification.com/campaign/",
    DeleteMailEndpoint: "https://test-api.brame-gamification.com/mail/mailType/"
}
