export default 
{
    Auth: 'Bearer eyJhbGciOiJSUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJZY1N2ZUZabUswYzV1cmpOM3FnYmF1aU1wbE1oWnBUTEF3bFExRUk5T09JIn0.eyJleHAiOjE2NjY5ODcxMjYsImlhdCI6MTY2Njk0MzkyNiwianRpIjoiOWYyMzE3YzAtMjY1YS00NDQ3LWJjMmItOTNlYjY0NTM3NzM1IiwiaXNzIjoiaHR0cHM6Ly9zdGFnZS1hcGkuYnJhbWUtZ2FtaWZpY2F0aW9uLmNvbS9rZXljbG9hay9hdXRoL3JlYWxtcy9icmFtZSIsImF1ZCI6ImFjY291bnQiLCJzdWIiOiI2ZGRlZTUwYi01MjkzLTQ1MTYtOTRkZS1hYTk3ZmZmNjMwNzQiLCJ0eXAiOiJCZWFyZXIiLCJhenAiOiJmZS1jbGllbnQiLCJzZXNzaW9uX3N0YXRlIjoiMzQ1NjQ4OWMtNWQ4OC00ZGQ2LTk0NGUtZTU1YjBmNGQ3YzFkIiwiYWNyIjoiMSIsImFsbG93ZWQtb3JpZ2lucyI6WyJzdGFnZS1hcHAuYnJhbWUtZ2FtaWZpY2F0aW9uLmNvbSIsImh0dHBzOi8vc3RhZ2UtYXBwLmJyYW1lLWdhbWlmaWNhdGlvbi5jb20iXSwicmVhbG1fYWNjZXNzIjp7InJvbGVzIjpbIkVESVRPUiIsIlZJRVdFUiJdfSwicmVzb3VyY2VfYWNjZXNzIjp7ImFjY291bnQiOnsicm9sZXMiOlsibWFuYWdlLWFjY291bnQiLCJtYW5hZ2UtYWNjb3VudC1saW5rcyIsInZpZXctcHJvZmlsZSJdfX0sInNjb3BlIjoiZW1haWwgcHJvZmlsZSIsImVtYWlsX3ZlcmlmaWVkIjpmYWxzZSwicm9sZSI6WyJFRElUT1IiLCJWSUVXRVIiXSwiY29tcGFueV9pZCI6IjYzODYyNGUyLWE2NTgtNDg1Mi1hM2NjLTM3YWE0ZDkyMGMzOSIsIm5hbWUiOiJOZW1hbmphIENpcmtvdmljIiwicHJlZmVycmVkX3VzZXJuYW1lIjoiY2lyYUBicmFtZS5jaCIsImdpdmVuX25hbWUiOiJOZW1hbmphIiwiZmFtaWx5X25hbWUiOiJDaXJrb3ZpYyIsImVtYWlsIjoiY2lyYUBicmFtZS5jaCJ9.TXsLWhTBFGJOiXXFmwKZH4zYtNoyl8H8apZhUKJmLQYCCBpP5hd1hiGfJyhGcOpgNPDnNlBDeOADYS0d6wn3woeE6xrCqq8QuZ42g7ouyNBQSNSZZiKKk9QO6rcQJbzViiIdxoAnNuFN8Tv3fbVxkMj41b7K1_awHo2so4iJqFiN1FYztCYvKUzcZWlEk1naCMXNodo9I4lYSkJIXlwvdeoWotr4I-Lz4wU9G5O4PsjYvGQnAlhhrMVV55nxrECz4HbL22uXM5d3ble0vN0CWHwg9HoIkSq1jWCCrCvVlTlLiAuCt1UuLSUIGUZTTE-yvZ55CmsXiBX6U3D2l7H_ZA',
    CompanyId: '638624e2-a658-4852-a3cc-37aa4d920c39',
    PostPrizeEndpoint: 'https://stage-serverless-api.brame-gamification.com/prize-management/prizes',
    DeletePrizeEndpoint: 'https://stage-serverless-api.brame-gamification.com/prize-management/prizes/delete/',
    PostPoolEndpoint: "https://stage-serverless-api.brame-gamification.com/prize-management/pools/",
    DeletePoolEndpoint: "https://stage-serverless-api.brame-gamification.com/prize-management/pools/delete",
    GetCampaignEndpoint: "https://stage-api.brame-gamification.com/campaign/search",
    DeleteCampaignEndpoint: "https://stage-api.brame-gamification.com/campaign/",
    DeleteMailEndpoint: "https://stage-api.brame-gamification.com/mail/mailType/"
}
